# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ICareOnline' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ICareOnline

  target 'ICareOnlineTests' do

	pod 'BubbleTabBar', '~> 0.9'

    inherit! :search_paths
    # Pods for testing
  end

  target 'ICareOnlineUITests' do
    # Pods for testing
  end

end
